---
- name: 安装并配置 Snort 入侵检测系统
  hosts: hosts
  become: yes
  vars_files:
    - group_vars/all.yml
  tasks:
    - name: 安装依赖包
      dnf:
        name:
          - openssl-devel
          - cmake
          - libpcap-devel
          - pcre2-devel
          - pcre-devel
          - hwloc-devel
          - zlib-devel
          - luajit-devel
          - pkgconf
          - libmnl-devel
          - libunwind-devel
          - libnfnetlink-devel
          - libnetfilter_queue
          - libnetfilter_queue-devel
          - gcc-c++
          - git
          - autoconf
          - automake
          - xz-devel
          - libuuid-devel
          - hyperscan
          - hyperscan-devel
          - gperftools-devel
          - libtool
          - flex
          - bison
        state: present

    - name: 验证 cmake 版本
      command: cmake --version
      register: cmake_version_output
      changed_when: false

    - name: 输出 cmake 版本信息
      debug:
        msg: "{{ cmake_version_output.stdout }}"

    - name: 安装 LibDAQ
      block:
        - name: 检查 libdaq 是否已安装（检查库文件）
          stat:
            path: /usr/local/lib/libdaq.so
          register: libdaq_installed

        - name: 克隆 LibDAQ 仓库
          git:
            repo: "https://github.com/snort3/libdaq.git"
            dest: "/tmp/libdaq"
            update: yes
          when: not libdaq_installed.stat.exists

        - name: 构建并安装 LibDAQ
          shell: |
            set -e
            ./bootstrap
            ./configure --prefix=/usr/local
            make -j$(nproc)
            make install
            ldconfig
          args:
            chdir: /tmp/libdaq
          when: not libdaq_installed.stat.exists
          environment:
            PKG_CONFIG_PATH: "/usr/local/lib/pkgconfig:/usr/lib/pkgconfig:/usr/local/lib64/pkgconfig:/usr/lib64/pkgconfig"

    - name: 检查是否已安装 snort 二进制
      stat:
        path: "{{ snort_install_dir }}/bin/snort"
      register: snort_installed

    - name: 安装 Snort
      block:
        - name: 克隆 Snort 源码
          git:
            repo: "https://github.com/snort3/snort3.git"
            dest: "/tmp/snort3"
            update: yes
          when: not snort_installed.stat.exists

        - name: 运行 configure_cmake.sh
          shell: |
            export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/usr/lib/pkgconfig:/usr/local/lib64/pkgconfig:/usr/lib64/pkgconfig
            export CFLAGS="-O3"
            export CXXFLAGS="-O3 -fno-rtti"
            ./configure_cmake.sh --prefix={{ snort_install_dir }} --enable-tcmalloc
          args:
            chdir: /tmp/snort3
          when: not snort_installed.stat.exists
          environment:
            PKG_CONFIG_PATH: "/usr/local/lib/pkgconfig:/usr/lib/pkgconfig:/usr/local/lib64/pkgconfig:/usr/lib64/pkgconfig"

        - name: 在 build 目录编译 Snort
          shell: make -j$(nproc)
          args:
            chdir: /tmp/snort3/build
          when: not snort_installed.stat.exists

        - name: 安装 Snort
          shell: make install
          args:
            chdir: /tmp/snort3/build
          when: not snort_installed.stat.exists

        - name: 在 /usr/local/bin 建立 snort 符号链接（保证命令可用）
          file:
            src: "{{ snort_install_dir }}/bin/snort"
            dest: /usr/local/bin/snort
            state: link
            force: yes

    - name: 验证 Snort 安装
      command: "{{ snort_install_dir }}/bin/snort --version"
      register: snort_version_output
      changed_when: false
      failed_when: false

    - name: 验证 snort 可执行
      command:
        argv:
          - "{{ snort_install_dir }}/bin/snort"
          - "--version"
      register: snort_version_output
      changed_when: false
      failed_when: false

    - name: 显示 snort --version 的完整注册结构
      debug:
        var: snort_version_output

    - name: 配置网卡为混杂模式
      ansible.builtin.shell:
        cmd: ip link set dev {{ interface }} promisc on

    - name: 检查网卡是否设置为混杂模式
      ansible.builtin.shell:
        cmd: ip link show dev {{ interface }}
      register: interface_status
      changed_when: false

    - name: 输出网卡状态
      debug:
        msg: "{{ interface_status.stdout }}"

    - name: 检查网卡卸载状态
      ansible.builtin.shell:
        cmd: "ethtool -k {{ interface }} | grep receive-offload"
      register: offload_status
      changed_when: false

    - name: 输出网卡卸载状态
      debug:
        msg: "{{ offload_status.stdout }}"

    - name: 创建 snort 网络接口 systemd 单元
      template:
        src: "snort3-nic.service.j2"
        dest: "/etc/systemd/system/snort3-nic.service"
        owner: root
        group: root
        mode: "0644"
      notify:
        - snort-daemon-reload
        - restart-snort3-nic

    - name: 确保 snort 用户存在
      user:
        name: snort
        state: present
        system: yes
        shell: /sbin/nologin
        create_home: no

    - name: 创建 Snort 目录结构
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ snort_user }}"
        group: "{{ snort_group }}"
        mode: '0755'
      loop:
        - "{{ snort_install_dir }}"
        - "{{ snort_config_dir }}"
        - "{{ snort_rules_dir }}"

    - name: 创建日志目录
      file:
        path: "/var/log/snort"
        state: directory
        owner: snort
        group: snort
        mode: '5775'

    - name: 检查 Snort3 源码目录结构
      block:
        - name: 检查 Snort3 源码目录
          stat:
            path: /tmp/snort3
          register: snort_src_dir

        - name: 列出 Snort3 源码目录内容
          command: find /tmp/snort3 -name "*.lua" -type f
          register: lua_files
          changed_when: false
          when: snort_src_dir.stat.exists

        - name: 显示找到的 Lua 文件
          debug:
            msg: "找到的 Lua 文件: {{ lua_files.stdout_lines }}"
          when: snort_src_dir.stat.exists

    - name: 复制 Lua 配置文件（安全方式）
      block:
        - name: 复制 snort_defaults.lua
          command: cp /tmp/snort3/lua/snort_defaults.lua "{{ snort_config_dir }}/"
          args:
            creates: "{{ snort_config_dir }}/snort_defaults.lua"
          when: snort_src_dir.stat.exists

        - name: 复制其他 Lua 文件
          find:
            paths: /tmp/snort3
            patterns: "*.lua"
            file_type: file
            recurse: yes
          register: all_lua_files
          when: snort_src_dir.stat.exists

        - name: 复制所有找到的 Lua 文件
          copy:
            src: "{{ item.path }}"
            dest: "{{ snort_config_dir }}/{{ item.path | basename }}"
            owner: "{{ snort_user }}"
            group: "{{ snort_group }}"
            mode: '0644'
            remote_src: yes
          loop: "{{ all_lua_files.files }}"
          when: 
            - snort_src_dir.stat.exists
            - all_lua_files.files | length > 0
          ignore_errors: yes

      rescue:
        - name: 处理文件复制错误
          debug:
            msg: "某些 Lua 文件复制失败，将继续使用基础配置"

    - name: 修复 file_magic.lua 配置问题
      block:
        - name: 创建正确的 file_magic.lua 配置
          copy:
            dest: "{{ snort_config_dir }}/file_magic.lua"
            content: |
              -- Snort3 文件魔术数字配置
              file_magic = 
              {
                  { type = "PDF document", magic = "\\x25\\x50\\x44\\x46" },
                  { type = "ZIP archive", magic = "\\x50\\x4B\\x03\\x04" },
                  { type = "GZIP compressed", magic = "\\x1F\\x8B\\x08" },
                  { type = "RAR archive", magic = "\\x52\\x61\\x72\\x21\\x1A\\x07\\x00" },
                  { type = "Windows PE executable", magic = "\\x4D\\x5A" },
                  { type = "ELF executable", magic = "\\x7F\\x45\\x4C\\x46" },
                  { type = "JPEG image", magic = "\\xFF\\xD8\\xFF\\xE0" },
                  { type = "PNG image", magic = "\\x89\\x50\\x4E\\x47\\x0D\\x0A\\x1A\\x0A" },
                  { type = "GIF image", magic = "GIF8" },
                  { type = "Windows BMP image", magic = "BM" },
                  { type = "TIFF image", magic = "\\x49\\x49\\x2A\\x00" },
                  { type = "Microsoft Office document", magic = "\\xD0\\xCF\\x11\\xE0\\xA1\\xB1\\x1A\\xE1" },
                  { type = "Java class", magic = "\\xCA\\xFE\\xBA\\xBE" },
                  { type = "Mach-O executable", magic = "\\xFE\\xED\\xFA\\xCE" },
                  { type = "Mach-O executable 64-bit", magic = "\\xFE\\xED\\xFA\\xCF" },
                  { type = "Windows shortcut", magic = "\\x4C\\x00\\x00\\x00\\x01\\x14\\x02\\x00" },
                  { type = "HTML document", magic = "<html" },
                  { type = "XML document", magic = "<?xml" },
              }
            owner: "{{ snort_user }}"
            group: "{{ snort_group }}"
            mode: '0644'

        - name: 验证配置文件语法（使用 dofile 而不是 require）
          command: lua -e "dofile('{{ snort_config_dir }}/file_magic.lua'); print('file_magic.lua syntax OK')"
          register: lua_syntax_check
          changed_when: false
          failed_when: false

        - name: 显示 Lua 语法检查结果
          debug:
            msg: "Lua 语法检查: {{ lua_syntax_check.stdout }}"
          when: lua_syntax_check.rc == 0

        - name: 显示 Lua 语法检查错误
          debug:
            msg: "Lua 语法检查失败: {{ lua_syntax_check.stderr }}"
          when: lua_syntax_check.rc != 0

    - name: 创建基础配置文件（如果源码文件不存在）
      block:
        - name: 检查是否已复制 snort_defaults.lua
          stat:
            path: "{{ snort_config_dir }}/snort_defaults.lua"
          register: defaults_check

        - name: 创建基础 snort_defaults.lua
          copy:
            dest: "{{ snort_config_dir }}/snort_defaults.lua"
            content: |
              -- 基础 Snort 默认配置
              root = 
              {
                  base = "{{ snort_install_dir }}",
                  daemon = nil,
                  logdir = "/var/log/snort",
                  ruletest = false,
              }
            owner: "{{ snort_user }}"
            group: "{{ snort_group }}"
            mode: '0644'
          when: not defaults_check.stat.exists

    - name: 创建主配置文件
      template:
        src: "snort.lua.j2"
        dest: "{{ snort_config_dir }}/snort.lua"
        owner: "{{ snort_user }}"
        group: "{{ snort_group }}"
        mode: '0644'

    - name: 验证配置文件已创建
      stat:
        path: "{{ snort_config_dir }}/{{ item }}"
      loop:
        - "snort.lua"
        - "snort_defaults.lua"
        - "file_magic.lua"
      register: config_files

    - name: 显示配置文件状态
      debug:
        msg: "配置文件 {{ item.item }} 存在: {{ item.stat.exists }}"
      loop: "{{ config_files.results }}"

    - name: 添加snort规则
      block:
        - name: 下载Snort规则集
          get_url:
            url: "{{ community_rules_url }}"
            dest: "/tmp/snort3-community-rules.tar.gz"
            mode: '0644'

        - name: 解压Snort规则集
          unarchive:
            src: "/tmp/snort3-community-rules.tar.gz"
            dest: "{{ snort_rules_dir }}"
            remote_src: yes
            owner: "{{ snort_user }}"
            group: "{{ snort_group }}"

        - name: 创建本地规则文件
          copy:
            dest: "{{ snort_rules_dir }}/local.rules"
            content: |
              alert icmp any any -> {{ home_net }} any (msg:"ICMP Packet Detected"; sid:1000001; rev:1;)
            owner: "{{ snort_user }}"
            group: "{{ snort_group }}"
            mode: '0644'

    - name: 安装 OpenAppID 扩展
      block:
        - name: 下载 OpenAppID
          get_url:
            url: "https://www.snort.org/downloads/openappid/33380"
            dest: "/tmp/OpenAppId-33380.tgz"
            mode: '0644'

        - name: 创建 OpenAppID 目录
          file:
            path: "{{ snort_install_dir }}/lib/openappid"
            state: directory
            owner: "{{ snort_user }}"
            group: "{{ snort_group }}"
            mode: '0755'

        - name: 解压 OpenAppID 扩展
          unarchive:
            src: "/tmp/OpenAppId-33380.tgz"
            dest: "{{ snort_install_dir }}/lib/openappid"
            remote_src: yes
            owner: "{{ snort_user }}"
            group: "{{ snort_group }}"

    - name: 测试 Snort 配置 (snort -T)
      block:
        - name: 运行 Snort 配置测试
          command:
            argv:
              - "{{ snort_install_dir }}/bin/snort"
              - "-c"
              - "{{ snort_config_dir }}/snort.lua"
              - "-T"
          register: snort_config_test
          environment:
            SNORT_LUA_PATH: "{{ snort_config_dir }}/?.lua"
          failed_when: false
          changed_when: false

        - name: 检查配置测试结果
          debug:
            msg: |
              Snort 配置测试完成
              退出代码: {{ snort_config_test.rc }}
              加载规则数: {{ snort_config_test.stdout | regex_findall('total rules loaded: (\\d+)') | first | default('未知') }}
              错误: {{ snort_config_test.stderr | default('无') }}

        - name: 如果配置测试失败但规则已加载，标记为警告而非错误
          debug:
            msg: "警告: Snort 配置测试有错误，但规则已成功加载。可以继续安装。"
          when: 
            - snort_config_test.rc != 0
            - "'total rules loaded:' in snort_config_test.stdout"
      when: config_files.results | selectattr("stat.exists") | list | length >= 2

    - name: 最终验证 Snort 安装
      block:
        - name: 验证 Snort 基本功能
          command: "{{ snort_install_dir }}/bin/snort --help"
          register: snort_help
          changed_when: false
          failed_when: false

        - name: 显示 Snort 帮助信息摘要
          debug:
            msg: "Snort 版本: {{ snort_version_output.stdout }}"

    - name: 创建 snort3 systemd 服务单元
      template:
        src: "snort3.service.j2"
        dest: "/etc/systemd/system/snort3.service"
        owner: root
        group: root
        mode: "0644"
      notify:
        - snort-daemon-reload
        - restart-snort3

    - name: 清理临时文件
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /tmp/libdaq
        - /tmp/snort3
        - /tmp/snort3-community-rules.tar.gz
        - /tmp/OpenAppId-33380.tgz
      ignore_errors: yes

  handlers:
    - name: snort-daemon-reload
      systemd:
        daemon_reload: yes

    - name: restart-snort3-nic
      systemd:
        name: snort3-nic.service
        state: restarted

    - name: restart-snort3
      systemd:
        name: snort3.service
        state: restarted